### PR TITLE
Added option to ignore draggable elements

### PR DESCRIPTION
**Pull request by dplantera**
Hi, 
I am currently working on a pet project to dive into css and js. I was happy to find your library on Github - Thank your very much. 

However, for my usecase (draging images), I needed to adapt the event listner, otherwise I was not able to drag Images.

Maybe this is usefull for someone else as well.

### CODE REVIEW

**Comment by kmturley** [comment]
Awesome, are you able to add a demo <div> to index.html show how it works?

**Comment by Tango1266** [comment]
Sure, this or next week I will come up with an appropriate demo and add it to this PR.

**Comment by Tango1266** [comment]
I added a demo and I tried to stay as simple as possible. It supports IE and Chrome Desktop. 

You may notice that I removed the a-Tags in the new carousel. With them I would not be able to reproduce my issue with the lib. In my pet project it was easier for me to extend the lib then my source code.

**Comment by kmturley** [comment]
Looks great! thanks for the PR

**Pull request merged**
